import { BadRequestException, Injectable, NotFoundException } from '@nestjs/common';
import { CouponStatus, DeliveryStatus } from '@prisma/client';
import { PrismaService } from '../prisma/prisma.service';
import { ImportCouponsDto, UpdateCampaignDto } from './admin.dto';

@Injectable()
export class AdminService {
  constructor(private readonly prisma: PrismaService) {}
  private async campaign() { const campaign = await this.prisma.campaign.findFirst({ orderBy: { createdAt: 'desc' } }); if (!campaign) throw new NotFoundException('Nenhuma campanha encontrada.'); return campaign; }
  private audit(campaignId: string, action: string, metadata?: object) { return this.prisma.adminAuditLog.create({ data: { campaignId, action, metadata } }); }
  async dashboard() { const campaign = await this.campaign(); const [submissions, available, assigned, deliveries] = await Promise.all([this.prisma.submission.count({ where: { campaignId: campaign.id } }), this.prisma.coupon.count({ where: { campaignId: campaign.id, status: CouponStatus.AVAILABLE } }), this.prisma.coupon.count({ where: { campaignId: campaign.id, status: CouponStatus.ASSIGNED } }), this.prisma.deliveryRequest.groupBy({ by: ['status'], _count: { _all: true }, where: { submission: { campaignId: campaign.id } } })]); return { campaign: { slug: campaign.slug, title: campaign.title, active: campaign.active }, submissions, coupons: { available, assigned }, deliveries: Object.fromEntries(deliveries.map((item) => [item.status, item._count._all])) }; }
  async participants(query?: string, status?: DeliveryStatus) { const campaign = await this.campaign(); return this.prisma.submission.findMany({ where: { campaignId: campaign.id, ...(query ? { OR: [{ name: { contains: query, mode: 'insensitive' } }, { phone: { contains: query } }] } : {}), ...(status ? { delivery: { status } } : {}) }, orderBy: { createdAt: 'desc' }, select: { id: true, name: true, phone: true, answers: true, createdAt: true, coupon: { select: { code: true } }, delivery: { select: { status: true, updatedAt: true } } } }); }
  async getCampaign() { const campaign = await this.campaign(); return this.prisma.campaign.findUnique({ where: { id: campaign.id }, include: { questions: { orderBy: { position: 'asc' } } } }); }
  async updateCampaign(dto: UpdateCampaignDto) { const campaign = await this.campaign(); const updated = await this.prisma.campaign.update({ where: { id: campaign.id }, data: { ...(dto.active === undefined ? {} : { active: dto.active }), ...(dto.title === undefined ? {} : { title: dto.title.trim() }), ...(dto.subtitle === undefined ? {} : { subtitle: dto.subtitle.trim() }) } }); await this.audit(campaign.id, 'CAMPAIGN_UPDATED', dto); return updated; }
  async coupons(query?: string, status?: CouponStatus) { const campaign = await this.campaign(); return this.prisma.coupon.findMany({ where: { campaignId: campaign.id, ...(status ? { status } : {}), ...(query ? { code: { contains: query, mode: 'insensitive' } } : {}) }, orderBy: { createdAt: 'desc' }, include: { submission: { select: { name: true, createdAt: true } } } }); }
  async importCoupons(dto: ImportCouponsDto) { const campaign = await this.campaign(); const codes = [...new Set(dto.codes.map((code) => code.trim().toUpperCase()).filter(Boolean))]; if (!codes.length) throw new BadRequestException('Nenhum código válido foi informado.'); const result = await this.prisma.coupon.createMany({ data: codes.map((code) => ({ campaignId: campaign.id, code })), skipDuplicates: true }); await this.audit(campaign.id, 'COUPONS_IMPORTED', { received: dto.codes.length, inserted: result.count }); return { inserted: result.count, ignored: codes.length - result.count }; }
  async deliveries(status?: DeliveryStatus) { const campaign = await this.campaign(); return this.prisma.deliveryRequest.findMany({ where: { submission: { campaignId: campaign.id }, ...(status ? { status } : {}) }, orderBy: { updatedAt: 'desc' }, include: { submission: { select: { id: true, name: true, phone: true, coupon: { select: { code: true } } } } } }); }
  async history() { const campaign = await this.campaign(); return this.prisma.adminAuditLog.findMany({ where: { campaignId: campaign.id }, orderBy: { createdAt: 'desc' }, take: 100 }); }
  async logResend(submissionId: string) { const submission = await this.prisma.submission.findUnique({ where: { id: submissionId }, select: { campaignId: true } }); if (!submission) throw new NotFoundException('Participante não encontrado.'); await this.audit(submission.campaignId, 'DELIVERY_RESEND_REQUESTED', { submissionId }); }
}
